### ISSUE TITLE
Copy and Paste menu options not available in linux

### ISSUE THREAD

**Issue by gnomed** [AshKyd/alchemize#3]
![screenshot from 2017-04-26 15-49-50](https://cloud.githubusercontent.com/assets/7014500/25456311/22216060-2a98-11e7-95ce-dd891f93550c.png)
The copy and paste options are not available from the context menu on linux.

Ubuntu 16.04 LTS
Latest Chrome

**Comment by AshKyd** [comment]
Ah that's a shame I didn't see this one. I've just bumped the editor version and published to the PWA here: https://alchemizeapp.com/app/

I'm gonna close this one 'cos I can't verify it at the moment, but feel free to open it if you still have the issue.
