### ISSUE TITLE
Can't compress or prettify

### ISSUE THREAD

**Issue by sekedus** [AshKyd/alchemize#5]
Can't compress or prettify, only show progress bar.

Browser: Chrome 103.0.5060.134 (Official Build) (64-bit)
Alchemize: web version

![alchemize-bug](https://user-images.githubusercontent.com/25115799/193366636-cd37a1cb-89b7-4122-9aa8-3e0c298e4005.png)

**Comment by AshKyd** [comment]
Thanks @sekedus, the build messed up with a missing dependency when I moved it to a new server. I just fixed it so it should be working now if you refresh (and if that doesn't work, try a hard refresh).
